# Documentation about Garden projects can be found at https://docs.garden.io/using-garden/projects
# Reference for Garden projects can be found at https://docs.garden.io/reference/project-config

apiVersion: garden.io/v1
kind: Project
name: gardenbot

defaultEnvironment: local

# Environments typically represent different stages of your development and deployment process.
environments:
  # Use this environment to develop in your local Kubernetes solution of choice.
  # Installation instructions and list of supported local Kubernetes environments: https://docs.garden.io/kubernetes-plugins/local-k8s/install
  - name: local
    defaultNamespace: garden-local

  # Use this environment to develop in remote, production-like environments that scale with your stack.
  # This means you don't need any dependencies on your local machine, even the builds can be performed remotely.
  # It enables sharing build and test caches with your entire team, which can significantly speed up pipelines and development.
  - name: remote
    defaultNamespace: garden-remote-${local.username}

  - name: staging
    # Ask before performing potentially destructive commands like "deploy".
    production: true
    defaultNamespace: staging

# Providers make action types available in your Garden configuration and tell Garden how to connect with your infrastructure.
# For example the kubernetes and local-kubernetes providers allow you to use the container, helm and kubernetes action types.
# All available providers and their configuration options are listed in the reference docs: https://docs.garden.io/reference/providers
providers:
  - name: local-kubernetes
    context: rancher-desktop
    environments:
      - local

  # To configure the remote kubernetes providers, follow the steps at https://docs.garden.io/kubernetes-plugins/remote-k8s
  - name: kubernetes
    environments:
      - remote
    context: # ... your remote development kubecontext here
  - name: kubernetes
    environments:
      - staging
    context: # ... your staging kubecontext here

# Next step: Define actions to tell Garden how to build, test and deploy your code.
# You can find out more here: https://docs.garden.io/using-garden/actions
